version: '3.3'
services:

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./proninteam/static:/var/html/static
    depends_on:
     - backend
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./environment/.env
  backend:
    build:
      context: .
      dockerfile: ./proninteam/Dockerfile
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - ./static:/project/static
    env_file:
      - ./environment/.env
    environment:
      - WATHCPACK_POLLING=true
