version: '3.3'
services:

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8080:80"
    volumes:
      - ./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static
      - media:/var/html/media
    depends_on:
     - backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./environment/.env

  backend:
    build:
      context: ./proninteam
    restart: always
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
    env_file:
      - ./environment/.env
    environment:
      - WATHCPACK_POLLING=true

volumes:
  media:
  static:
